# Generated by Django 3.0.2 on 2020-01-26 13:22

from django.db import migrations, models
import django.db.models.deletion
import v1.payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0005_auto_20200126_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=v1.payments.models.keygen_hex, max_length=30, primary_key=True, serialize=False)),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('productinfo', models.TextField(verbose_name='Product Info')),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('address1', models.CharField(max_length=100, verbose_name='Address 1')),
                ('address2', models.CharField(max_length=100, verbose_name='Address 2')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('zipcode', models.CharField(max_length=50, verbose_name='Zip Code')),
                ('udf1', models.TextField(blank=True, null=True, verbose_name='user defined 1')),
                ('udf2', models.TextField(blank=True, null=True, verbose_name='user defined 2')),
                ('udf3', models.TextField(blank=True, null=True, verbose_name='user defined 3')),
                ('udf4', models.TextField(blank=True, null=True, verbose_name='user defined 4')),
                ('udf5', models.TextField(blank=True, null=True, verbose_name='user defined 5')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.Business', verbose_name='Business')),
            ],
        ),
    ]
