# Generated by Django 3.0.2 on 2020-01-26 14:50

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=django_mysql.models.EnumField(choices=[('request', 'request'), ('success', 'success'), ('failure', 'failure')], default='request'),
        ),
    ]
