# Generated by Django 3.0.2 on 2020-01-26 15:05

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200126_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=django_mysql.models.EnumField(choices=[('INR', 'Indian Rupees')], default='INR', verbose_name='Currency'),
        ),
    ]
