# Generated by Django 3.0.2 on 2020-01-26 19:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAccessKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='key')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_key', to='payments.Transaction')),
            ],
        ),
    ]
