# Generated by Django 3.0.2 on 2020-01-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_businessapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='payu_key',
            field=models.CharField(default='foo', max_length=50, verbose_name='PayU Key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='payu_salt',
            field=models.CharField(default='foo', max_length=50, verbose_name='PayU Salt'),
            preserve_default=False,
        ),
    ]
